server:
  port: ":8080"
datasource:
  host: 127.0.0.1
  port: 3307
  database: tiktok_e-commence
  username: root
  password: "041212"
  charset: utf8mb4
redis:
  addr: "localhost:6380"
consul:
  addr: "127.0.0.1:8500"
logger:
  level: info
  prefix: '[blog]'
  director: log
  show_line: true
  log_in_console: true